import pytest
from fastapi.testclient import TestClient
import jwt
from app.main import app
from app.database.connection import get_db, SessionLocal
from app.models.domain import Unit
import tempfile
import os
import shutil
import uuid
from sqlcipher3 import dbapi2 as sqlite3

client = TestClient(app)

def create_mock_token(email="marcelo.romero@rededor.com.br", oid="12345-67890-superadmin", tid="tenant-xyz"):
    payload = {
        "oid": oid,
        "tid": tid,
        "preferred_username": email,
        "name": "Super Admin Mock",
        "exp": 9999999999
    }
    return jwt.encode(payload, "secret", algorithm="HS256")

@pytest.fixture
def auth_headers():
    token = create_mock_token()
    return {"Authorization": f"Bearer {token}"}

@pytest.fixture(scope="module")
def db_session():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

def create_mock_db(filepath, valid=True, db_id=None):
    if db_id is None:
        db_id = str(uuid.uuid4())
    conn = sqlite3.connect(filepath)
    cursor = conn.cursor()
    
    # Needs the proper SQLCipher key context
    # Usually we bypass this if the test uses the same key_manager.
    # To properly mock a DB generated by NetworkMap, we must fetch the current dev key.
    from app.security.key_manager import get_or_create_database_key
    db_key = get_or_create_database_key()
    safe_key = db_key.replace("'", "''")
    cursor.execute(f"PRAGMA key = '{safe_key}'")
    
    if valid:
        cursor.execute('CREATE TABLE database_metadata (id INTEGER PRIMARY KEY, application_name TEXT, database_id TEXT, schema_version INTEGER, organization_id TEXT, created_by_version TEXT, created_at TEXT)')
        cursor.execute(f'INSERT INTO database_metadata (application_name, database_id, schema_version) VALUES (\'NetworkMap\', \'{db_id}\', 1)')
        cursor.execute('CREATE TABLE racks (id INTEGER PRIMARY KEY, uuid TEXT, unit_id INTEGER, name TEXT, location_description TEXT, description TEXT, notes TEXT, created_at TEXT, updated_at TEXT)')
        cursor.execute(f'INSERT INTO racks (uuid, name, location_description) VALUES (\'{str(uuid.uuid4())}\', \'Mock Rack\', \'Test Location\')')
        cursor.execute('CREATE TABLE switches (id INTEGER PRIMARY KEY, uuid TEXT, unit_id INTEGER, name TEXT, hostname TEXT, manufacturer TEXT, model TEXT, ip_address TEXT, mac_address TEXT, port_count INTEGER, rack_id INTEGER, rack_position TEXT, notes TEXT, created_at TEXT, updated_at TEXT)')
        cursor.execute('CREATE TABLE devices (id INTEGER PRIMARY KEY, uuid TEXT, unit_id INTEGER, name TEXT, hostname TEXT, ip_address TEXT, mac_address TEXT, device_type TEXT, location_id INTEGER, vlan_id INTEGER, manufacturer TEXT, model TEXT, asset_tag TEXT, serial_number TEXT, description TEXT, notes TEXT, created_at TEXT, updated_at TEXT)')
        cursor.execute('CREATE TABLE locations (id INTEGER PRIMARY KEY, uuid TEXT, unit_id INTEGER, name TEXT, sector TEXT, floor TEXT, description TEXT, notes TEXT, created_at TEXT, updated_at TEXT)')
        cursor.execute('CREATE TABLE vlans (id INTEGER PRIMARY KEY, uuid TEXT, unit_id INTEGER, vlan_number INTEGER, name TEXT, description TEXT, subnet TEXT, gateway TEXT, created_at TEXT, updated_at TEXT)')
        cursor.execute('CREATE TABLE switch_ports (id INTEGER PRIMARY KEY, uuid TEXT, unit_id INTEGER, switch_id INTEGER, port_number INTEGER, name TEXT, description TEXT, vlan_id INTEGER, destination_location_id INTEGER, connected_device_id INTEGER, connection_type TEXT, status TEXT, notes TEXT, created_at TEXT, updated_at TEXT)')
        cursor.execute('CREATE TABLE connections (id INTEGER PRIMARY KEY, uuid TEXT, unit_id INTEGER, source_port_id INTEGER, target_port_id INTEGER, description TEXT, created_at TEXT)')
    else:
        # Invalid schema
        cursor.execute("CREATE TABLE dummy (id INTEGER)")

    conn.commit()
    conn.close()
    return db_id

def test_import_invalid_extension(auth_headers):
    files = {'file': ('test.txt', b'dummy content', 'text/plain')}
    res = client.post("/api/admin/import", headers=auth_headers, files=files)
    assert res.status_code == 400
    assert "Somente arquivos .db são suportados" in res.json()["detail"]

def test_import_invalid_db(auth_headers):
    # Empty non-sqlite file
    with tempfile.NamedTemporaryFile(suffix=".db") as tmp:
        tmp.write(b"not a sqlite db")
        tmp.flush()
        files = {'file': ('invalid.db', open(tmp.name, 'rb'), 'application/octet-stream')}
        res = client.post("/api/admin/import", headers=auth_headers, files=files)
        assert res.status_code == 400
        assert "Chave do SQLCipher inválida ou arquivo corrompido" in res.json()["detail"]

def test_import_wrong_schema(auth_headers):
    with tempfile.NamedTemporaryFile(suffix=".db", delete=False) as tmp:
        pass
    try:
        create_mock_db(tmp.name, valid=False)
        files = {'file': ('wrong_schema.db', open(tmp.name, 'rb'), 'application/octet-stream')}
        res = client.post("/api/admin/import", headers=auth_headers, files=files)
        assert res.status_code == 400
        # If it fails to parse valid sqlite structure/decrypts bad it might throw the generic cipher error, or specific table error.
        assert "Chave do SQLCipher inválida ou arquivo corrompido" in res.json()["detail"] or "não possui as tabelas" in res.json()["detail"]
    finally:
        os.remove(tmp.name)

def test_import_success_and_duplicate(auth_headers, db_session):
    with tempfile.NamedTemporaryFile(suffix=".db", delete=False) as tmp:
        pass
    try:
        db_id = create_mock_db(tmp.name, valid=True)
        files = {'file': ('valid_import.db', open(tmp.name, 'rb'), 'application/octet-stream')}
        
        # First import should succeed
        res = client.post("/api/admin/import", headers=auth_headers, files=files)
        assert res.status_code == 200
        data = res.json()
        assert "sucesso" in data["message"]
        unit_id = data["new_unit_id"]
        
        # Verify unit created
        unit = db_session.query(Unit).filter_by(id=unit_id).first()
        assert unit is not None
        assert db_id in unit.description
        
        # Second import should fail due to duplicate detection
        files = {'file': ('valid_import_dup.db', open(tmp.name, 'rb'), 'application/octet-stream')}
        res2 = client.post("/api/admin/import", headers=auth_headers, files=files)
        assert res2.status_code == 409
        assert "já foi importado" in res2.json()["detail"]

    finally:
        os.remove(tmp.name)
